Views
Roland-Ntwali/Blog-App pull request #6
Opened 2023-07-20 18:23 UTC by Roland-Ntwali

### In this pull request, I did the following:

- Implement the design from the sneak peek wireframes
- Use preprocessed HTML file with embedded Ruby code
- Add user view
- Add post view

2023-07-20 20:00 UTC, OyePriscilla requested changes
Hi @Roland-Ntwali ✔️ , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
`Users controller #index` action rendered all users ✔️
`recent_post` method to rendered the user's 3 most recent post ❎
Used `post.recent_comments` rendered 5 most recent comments ✔️
`Post show page` displays post with all comments listed ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 20:00 UTC, OyePriscilla commented on app/views/users/show.html.erb
> +   <li class="list_name"> <%= @users.name %> </li>
- [ ] Kindly take note that for good user experience you ought to use the `link `element that will redirects users to the `users_post `page. 👍 I was only able to access the page by typing the `url `manually. ℹ️ 

- [ ] Kindly ensure that `three most recent posts` are displayed by default according to the project requirements. 👍

2023-07-20 20:00 UTC, OyePriscilla commented on app/views/posts/index.html.erb
> +            <li class="bio_content"> <%= post.text %> </li>
- [ ] Kindly take note that for good user experience you ought to use the `link` element that will redirects users to the `post_index `page. 👍 I was only able to access the page by typing the `url `manually. ℹ️ 
- [ ] For the sake of semantics, I think the h3 element supposed not to be in the unordered list `ul`. ℹ️

2023-07-21 13:33 UTC, Zuhaib042 approved these changes
Hi @Roland-Ntwali 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif)
## Highlights
✅ Well Done on implementing suggested changes

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 13:57 UTC, merged